
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftANDleftORAND EQ FIELD_NAME GE GT LE LPAREN LT NEQ NUM_VAL OR RPAREN STRING_VALexpression : LPAREN expression RPARENexpression : expression AND expressionexpression : expression OR expressionexpression : constraintvalue : NUM_VAL \n                | STRING_VALconstraint : FIELD_NAME EQ value\n                    | FIELD_NAME NEQ value\n                    | FIELD_NAME GE value\n                    | FIELD_NAME GT value\n                    | FIELD_NAME LE value\n                    | FIELD_NAME LT value'
    
_lr_action_items = {'LPAREN':([0,2,5,6,],[2,2,2,2,]),'FIELD_NAME':([0,2,5,6,],[4,4,4,4,]),'$end':([1,3,14,15,16,17,18,19,20,21,22,23,24,],[0,-4,-2,-3,-1,-7,-5,-6,-8,-9,-10,-11,-12,]),'AND':([1,3,7,14,15,16,17,18,19,20,21,22,23,24,],[5,-4,5,-2,-3,-1,-7,-5,-6,-8,-9,-10,-11,-12,]),'OR':([1,3,7,14,15,16,17,18,19,20,21,22,23,24,],[6,-4,6,6,-3,-1,-7,-5,-6,-8,-9,-10,-11,-12,]),'RPAREN':([3,7,14,15,16,17,18,19,20,21,22,23,24,],[-4,16,-2,-3,-1,-7,-5,-6,-8,-9,-10,-11,-12,]),'EQ':([4,],[8,]),'NEQ':([4,],[9,]),'GE':([4,],[10,]),'GT':([4,],[11,]),'LE':([4,],[12,]),'LT':([4,],[13,]),'NUM_VAL':([8,9,10,11,12,13,],[18,18,18,18,18,18,]),'STRING_VAL':([8,9,10,11,12,13,],[19,19,19,19,19,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,6,],[1,7,14,15,]),'constraint':([0,2,5,6,],[3,3,3,3,]),'value':([8,9,10,11,12,13,],[17,20,21,22,23,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_parens','filter_parser.py',72),
  ('expression -> expression AND expression','expression',3,'p_expression_and','filter_parser.py',76),
  ('expression -> expression OR expression','expression',3,'p_expression_or','filter_parser.py',80),
  ('expression -> constraint','expression',1,'p_expression_constraint','filter_parser.py',84),
  ('value -> NUM_VAL','value',1,'p_value','filter_parser.py',88),
  ('value -> STRING_VAL','value',1,'p_value','filter_parser.py',89),
  ('constraint -> FIELD_NAME EQ value','constraint',3,'p_constraint','filter_parser.py',93),
  ('constraint -> FIELD_NAME NEQ value','constraint',3,'p_constraint','filter_parser.py',94),
  ('constraint -> FIELD_NAME GE value','constraint',3,'p_constraint','filter_parser.py',95),
  ('constraint -> FIELD_NAME GT value','constraint',3,'p_constraint','filter_parser.py',96),
  ('constraint -> FIELD_NAME LE value','constraint',3,'p_constraint','filter_parser.py',97),
  ('constraint -> FIELD_NAME LT value','constraint',3,'p_constraint','filter_parser.py',98),
]
